### ISSUE TITLE
console: UserWarning: You have unused kwarg parameters in XXX

### ISSUE THREAD

**Issue by davehornik** [vladmandic/sd-extension-system-info#10]
Can we get a fix for this console spam ?
```
D:\Stable WEBUI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings. Warn(
D:\Stable WEBUI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in JSON, please remove them: {'lines': 56}
  warnings. Warn(
D:\Stable WEBUI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in JSON, please remove them: {'lines': 0}
  warnings. Warn(
D:\Stable WEBUI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in JSON, please remove them: {'lines': 41}
  warnings. Warn(
D:\Stable WEBUI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in JSON, please remove them: {'lines': 28}
  warnings. Warn(
D:\Stable WEBUI\stable-diffusion-webui\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'scale': 0.5}
  warnings. Warn(
  ```

**Comment by vladmandic** [comment]
a) why do you think those messages come from this extension? none of those are actually mentioned anywhere in the codebase.
b) there is a good reason why warnings are **disabled** by default in webui and you should only enable them when you excplicitly require them.

**Comment by davehornik** [comment]
These warns are not showing while using clean webui without extensions.
After enabling just yours they showed up.
Thats why I am assuming they are coming from your ext.

**Comment by vladmandic** [comment]
its actually webui that is sending params to any additional ui components that it attempts to register during startup.
so you'd get similar warnings for most of scripts/extensions with any user interface if they are not using those params.

but like i said, warnings are disabled by default and for a good reason - gradio is full of false-positive warnings and normal operations are nearly-impossible with warnings enabled. only reason to enable warnings is if you're doing code development and debugging something specific.
