### ISSUE TITLE
Unable to find VAE during start up with this extension enabled.

### ISSUE THREAD

**Issue by rushuna86** [vladmandic/sd-extension-system-info#15]
Couldn't find VAE named clearvae_variant.safetensors; using None instead
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(7): bad_prompt_version2-neg, badhandv4, badv5, easynegative, ng_deepnegative_v1_75t, pureerosface_v1, ulzzang-6500-v1.1
Model loaded in 2.1s (load weights from disk: 0.4s, create model: 0.2s, apply weights to model: 0.8s, apply half(): 0.3s, move model to device: 0.4s).

To create a public link, set `share=True` in `launch()`.
Startup time: 8.4s (import torch: 0.9s, import gradio: 0.6s, import ldm: 0.3s, other imports: 1.4s, load scripts: 3.4s, create ui: 1.6s, gradio launch: 0.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.46it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 31.17it/s]
Loading VAE weights specified in settings: D:\SD\WebUIX\models\VAE\ClearVAE_NansLess1.safetensors0:00<00:00, 35.61it/s]
Applying scaled dot product cross attention optimization.
VAE weights loaded.
Loading VAE weights specified in settings: D:\SD\WebUIX\models\VAE\clearvae_variant.safetensors
Applying scaled dot product cross attention optimization.
VAE weights loaded.

Inside WebUI will show the correct "clearvae_variant" as selected from dropdown, but it's not applied, until switch made to different vae and back. Have tested with this extension disabled and no error. have isolated it down to this extension, built-in + this = cannot find vae message.

**Comment by vladmandic** [comment]
ok, i think it should be fixed now.

**Comment by rushuna86** [comment]
still happening even after latest commit

**Comment by vladmandic** [comment]
am i missing something?
1. set vae to something specific in settings
2. restart server
3. observe that vae is loaded on startup

anyhow, start `webui --debug` and post log AFTER line "Entering start sequence"

**Comment by rushuna86** [comment]
sorry for not getting it is this an argument? because showing up as not a launch.py argument

**Comment by vladmandic** [comment]
yes, its a command line argument - just running `webui --debug` should be enough, its definitely a launch.py argument:
what version are you on? this was added quite some time ago...

**Comment by rushuna86** [comment]
i'm using a fork,

https://github.com/anapnoe/stable-diffusion-webui-ux

commit d6b4aeb

Windows 11,

**Comment by vladmandic** [comment]
that is different! if you're using a fork, report issue there. that fork is not up to date with this repo. it will be, but its not yet.
