### ISSUE TITLE
[Feature Request] Lora

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/sd-extension-system-info#2]
as Lora is supported by WebUI without extensions, would be a nice addition list it along Checkpoints, TI and NH

that's not major, but just to keep up with recent updates

**Comment by vladmandic** [comment]
sure, i'll add it.

**Comment by vladmandic** [comment]
done in <https://github.com/vladmandic/sd-extension-system-info/commit/63f6fe7cc8eb5586e822ebaddda85b6c03876127>
