### ISSUE TITLE
Does "Submit results" works recently?

### ISSUE THREAD

**Issue by evshiron** [vladmandic/sd-extension-system-info#23]
I have recently submited around 20 records, 6 of them are submitted from Google Colab, but none of them shows up in the `benchmark-raw.json`.

The only update I have observed is https://github.com/vladmandic/sd-data/actions/runs/5302594308/jobs/9597632535, which isn't submitted by me and not meaningful.

**Comment by vladmandic** [comment]
glad you spotted it, log submit was filtered out for the past two days, fixed now.
