### ISSUE TITLE
`py-cpuinfo` and cpu info

### ISSUE THREAD

**Issue by Bing-su** [vladmandic/sd-extension-system-info#3]
https://github.com/workhorsy/py-cpuinfo

Using `py-cpuinfo`, wouldn't it be possible to put cpu information as well?

This package is cross-platform and has no dependencies.

**Comment by vladmandic** [comment]
it would, just not sure what's the value? and as much as `py-cpuinfo` is cross platform, its quite system-intrusive (not to blame it as there is no clean way to get that info to start with).

if there is a good use-case, i'll add it. but i don't want to bring such a heavy dependency just to look nice.
