### ISSUE TITLE
how to delete data in the benchmark

### ISSUE THREAD

**Issue by speaknowpotato** [vladmandic/sd-extension-system-info#31]
hi @vladmandic , thanks so much for your useful tools. 
I tried the benchmark and submitted the results, but I just found out that there is some information I don't want to disclose to the public. 
Is there any way to delete some records in the benchmark? 
the id is 5812. 
thanks in advance.

**Comment by vladmandic** [comment]
i don't really see anything sensitive in that record, but totally your choice - deleted.
