### ISSUE TITLE
[Issue] Not displaying LyCORIS

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/sd-extension-system-info#32]
System Info is not displaying LyCORIS on both Models and Info object

Models...

### Available LyCORIS
```
 [
]
```

### Info object

```
lycos:  [
],
```

SD.Next Version: 9a007331 Mon Aug 7 13:27:13 2023 +0300
default config

**Comment by vladmandic** [comment]
i've completely removed functionality to display networks within system info in the latest versions.  
for that, users should use extra networks interface.
sorry about that.
