### ISSUE TITLE
[Feature] Copy Info button to post on Issues - Version Platform Description

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/sd-extension-system-info#33]
it is more like a suggestion to add a Bug Report Button, to copy info needed to fill Version Platform Description

where a user would copy info to post an issue, feature, etc  on SD Next,  with just one click, streamlining the process,

requiring users to post that info, while you choose exactly what is posted, on the order and format you want / need

Platform, Backend,  Pipeline, Torch,  GPU, Memory optimization, Cross-attention, etc 

that way you would be able to standardize what is posted, cos  atm each person chooses whatever they want, usually console log, but quite frequently nothing

hopefully with that less ppl will skip that step

**Comment by vladmandic** [comment]
except this extension is used by multiple repos, not just sdnext.
plus, don't get me wrong - but i want user to provide issue information manually as it means user has to think for more than 1sec before creating issue.
