### ISSUE TITLE
Memory optimization medvram-sdxl not recognized

### ISSUE THREAD

**Issue by ldaldrup** [vladmandic/sd-extension-system-info#38]
The sdxl specific memory optimization `medvram-sdxl` is not recognized in the `System Info` > `Memory optimization` field.

**A1111 docs**
- [Optimum SDXL Usage](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Optimum-SDXL-Usage)
- [Command Line Arguments and Settings](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings#:~:text=low%20VRAM%20usage.-,%2D%2Dmedvram%2Dsdxl,-None)

**System Info**
![image](https://github.com/vladmandic/sd-extension-system-info/assets/6494290/46583d1b-65b8-4273-b4ea-16dc4bb13c3e)

**webui-user.bat**
![image](https://github.com/vladmandic/sd-extension-system-info/assets/6494290/ebbf3822-554c-4cb9-a739-6f1e57ab782b)

**Comment by ldaldrup** [comment]
https://github.com/vladmandic/sd-extension-system-info/pull/39

**Comment by vladmandic** [comment]
fixed.
