### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'clientWidth')

### ISSUE THREAD

**Issue by Coloured-glaze** [vladmandic/sd-extension-system-info#41]
![屏幕截图 2023-10-10 205255](https://github.com/vladmandic/sd-extension-system-info/assets/63091327/df0c832c-cf59-4b9b-98bf-df65f4ca5baa)
![屏幕截图 2023-10-10 205026](https://github.com/vladmandic/sd-extension-system-info/assets/63091327/85f8ae15-f29b-464f-a7d5-1eca36e1ad4c)

**Comment by vladmandic** [comment]
fixed.
