### ISSUE TITLE
Benchmark error: 'Field' object has no attribute 'alwayson_scripts'

### ISSUE THREAD

**Issue by splineclaw** [vladmandic/sd-extension-system-info#43]
## Summary
Whenever running the benchmark, all runs error with the console message
`SD-System-Info: benchmark error: 1 'Field' object has no attribute 'alwayson_scripts'`.

I have disabled all non-system extensions. 
SDNext and all extensions are up to date.
The issue persists across server restarts and system reboots.

## Details

Here's the error in context (in console):
```
16:17:24-839776 INFO     Model load finished: {'ram': {'used': 8.6, 'total': 23.88}, 'gpu': {'used': 3.12, 'total': 6.0}, 'retries': 0, 'oom': 0} cached=0
SD-System-Info: benchmark error: 1 'Field' object has no attribute 'alwayson_scripts'
16:17:24-853762 INFO     SD-System-Info: benchmark batch-size=1 it/s=error
16:17:24-859764 DEBUG    SD-System-Info: benchmark starting: batch-size=1
SD-System-Info: benchmark error: 1 'Field' object has no attribute 'alwayson_scripts'
16:17:24-863763 INFO     SD-System-Info: benchmark batch-size=1 it/s=error
16:17:24-866762 DEBUG    SD-System-Info: benchmark starting: batch-size=2
SD-System-Info: benchmark error: 2 'Field' object has no attribute 'alwayson_scripts'
16:17:24-870762 INFO     SD-System-Info: benchmark batch-size=2 it/s=error
16:17:24-877761 DEBUG    SD-System-Info: benchmark starting: batch-size=4
SD-System-Info: benchmark error: 4 'Field' object has no attribute 'alwayson_scripts'
16:17:24-881761 INFO     SD-System-Info: benchmark batch-size=4 it/s=error
16:17:24-886762 INFO     SD-System-Info: benchmark result: | 2023-11-29 16:17:24.859763 | error / error / error | app:SD.next updated:2023-11-27 hash:8136723f
                         url:https://github.com/vladmandic/automatic/tree/master | arch:AMD64 cpu:Intel64 Family 6 Model 94 Stepping 3, GenuineIntel system:Windows release:Windows-10-10.0.19045-SP0 python:3.10.8
                         | torch:2.1.0+cu118 Autocast  half xformers:0.0.22.post7+cu118 diffusers:0.23.1 transformers:4.35.2 | device:NVIDIA GeForce GTX 1060 (1) (compute_37) (6, 1) cuda:11.8 cudnn:8700
                         driver:536.40 6GB | original xFormers none | sd-v1-5-pruned-emaonly [cc6cb27103] | splineclaw |  | 6f474c |
16:17:24-903766 DEBUG    SD-System-Info: benchmark data saved: C:\sd\vladmandic\extensions-builtin\sd-extension-system-info\scripts\benchmark-data-local.json
```

Complete console log (with --debug):
[error-console.txt](https://github.com/vladmandic/sd-extension-system-info/files/13505661/error-console.txt)

Complete SDNext log (with --debug):
[sdnext - error.log](https://github.com/vladmandic/sd-extension-system-info/files/13505670/sdnext.-.error.log)

System Info screenshot:
![image](https://github.com/vladmandic/sd-extension-system-info/assets/37070764/6f7e3191-091b-47b2-9420-5e217f11bfe5)

## Related
I found [this SDNext issue (#2485)](https://github.com/vladmandic/automatic/issues/2485) mentioning the same error message but with third party plugins. It was flagged upstream. Consequently I have added and Issue here and not on SDNext.

**Comment by vladmandic** [comment]
you say you don't have extensions, but this seems like an upgrade from a VERY old installation that survived even after explicit recommendation to do clean install (which I do not do lightly) as several built-in extensions have been removed.

(even some settings seen in config are ancient). yes, in ideal world any upgrade would always be same to fresh-install, but in that world, new releases would come out 2 per year, not 2 per month.

so can you try clean install and reproduce this issue?

**Comment by splineclaw** [comment]
I've done a clean install (including fresh venv) and the issue persists. Same error message.

New logs:
[error-console-new.txt](https://github.com/vladmandic/sd-extension-system-info/files/13517044/error-console-new.txt)
[sdnext - error-new.log](https://github.com/vladmandic/sd-extension-system-info/files/13517046/sdnext.-.error-new.log)

**Comment by splineclaw** [comment]
After further testing, I found that if only sd-extension-system-info is enabled, it succeeds.
However, upon sd-webui-controlnet, it fails.

**Comment by vladmandic** [comment]
narrowing it down that much is very helpful, i'll look into it.
