### ISSUE TITLE
Add GPU temperture pls

### ISSUE THREAD

**Issue by 2575044704** [vladmandic/sd-extension-system-info#44]

**Comment by vladmandic** [comment]
system-info only uses torch api for gpu and temps are not available via that api. i don't plan to add secondary api interface to system info.

however, live monitoring using nvsmi interface is available in sd.next already - see screenshot below.

![image](https://github.com/vladmandic/sd-extension-system-info/assets/57876960/808e4d9e-63db-4e1e-8fc7-d191a4a0b119)
