### ISSUE TITLE
[IPEX] GPU name is blank in A1111 WebUI

### ISSUE THREAD

**Issue by zakusworo** [vladmandic/sd-extension-system-info#45]
When i'm use Intel Arc GPU with ipex, the GPU name is blank in system info and benchmark tab in A1111 WebUI. But in SD.Next it showed.

A1111
![image](https://github.com/vladmandic/sd-extension-system-info/assets/1959767/1ee3cdb9-aab1-430e-80ec-1c6a42c3f97e)

![image](https://github.com/vladmandic/sd-extension-system-info/assets/1959767/42cb057c-2540-4634-9b47-782cbb50d39c)

SD.Next
![image](https://github.com/vladmandic/sd-extension-system-info/assets/1959767/f2bc9fc1-700e-4e4e-bd34-edff62d586dc)

![image](https://github.com/vladmandic/sd-extension-system-info/assets/1959767/8a56bffe-272d-47b7-8f0c-ff813b870516)

**Comment by vladmandic** [comment]
a1111 does not have full ipex support.
