### ISSUE TITLE
[Online result viewer] Improve search function to allow multiple terms

### ISSUE THREAD

**Issue by feffy380** [vladmandic/sd-extension-system-info#46]
Currently the search bar in the benchmark viewer seems to be exact string matching. It would be nice to have the option to search for results matching multiple terms to allow more complex filtering like only showing results from 3060 12GB with optimizations: xformers, none.

Perhaps each keyword would be matched separately, with the option to use quotes for exact strings

**Comment by vladmandic** [comment]
its a good idea and valid request, but currently data display is done using [gridjs](https://github.com/grid-js/gridjs) library and it doesn't have that kind of a feature.
this would require basically a complete reimplementation of the search and that is out-of-scope at the moment.
