### ISSUE TITLE
Stopped working after last update

### ISSUE THREAD

**Issue by MigCurto** [vladmandic/sd-extension-system-info#47]
Hi, Im on a Mac , had no problems using extension until I updated to last version (yesterday date) trough Extensions pane in A1111 , already tried deleting folder, reinstalled but can't get System Info tab on A1111.

Lastest MacOSX - Mac Studio Ultra
![Screenshot 2024-01-22 at 18 10 03](https://github.com/vladmandic/sd-extension-system-info/assets/14836041/a9574d33-8c85-4b77-ac88-477481d54300)

Tks for the extension BTW

**Comment by pro-krastinator** [comment]
same here.
version: [v1.7.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cf2772fab0af5573da775e7437e6acdca424f26e)  •  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [48de823bb4](https://google.com/search?q=48de823bb480009015c95b32492a2c63880b84bfc10c606d69a94752152fc11b)

**Comment by vladmandic** [comment]
should be fixed now

**Comment by bkrew** [comment]
Same for me, just disappeared from tab:
python: 3.11.7  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2

**Comment by MigCurto** [comment]
> should be fixed now

Yes it is.Thank you Sir!

**Comment by pro-krastinator** [comment]
Yes, confirmed - fixed!
