### ISSUE TITLE
[Request] Move the System info tab to the end, and, Automatic hash calculator.

### ISSUE THREAD

**Issue by Nacurutu** [vladmandic/sd-extension-system-info#6]
It is possible to move the "system info" tab at the end of the tab list next to extensions?

As this is an important tab and not related to any of the Image tools extensions, could be better to have it next to Extensions and settings. 

Also, it is possible to have a Hash calculator in the system info tab?

I always prune my models to save disk space, and I think that changes the model's hash.. as your extension has access to the models and hashes, it is possible to make a script to create all HASHes for each model with one click? 

Like, look for all the models without HASH, calculate the HASH, and assign the hash to the model. 

If I'm not mistaken,  right now we need to select and use a model for the HASH to be calculated and assigned.

I have 493 models at the moment and less than 10% have the HASH.

**Comment by vladmandic** [comment]
i'd like if that was possible, but its webui that controls the layout.
i'll look into core webui code if i can make some layout customizations configurable.
closing here as not much can be done from the extension side.

**Comment by Nacurutu** [comment]
and what about the Automatic hash calculator option? :D

**Comment by vladmandic** [comment]
that should be doable, but why do you need a hash before you ever used a model?

there is also a problem of loading many models sequentially one after another due to memory leaks when switching models (much better in recent versions of webui, but still present on some systems) - so loading 100 models to generate hashes would likely cause a crash.

**Comment by Nacurutu** [comment]
Got it... thanks for your quick response!
