### ISSUE TITLE
Accidentally posted real name to database

### ISSUE THREAD

**Issue by f0lie** [vladmandic/sd-extension-system-info#7]
It seems like the username field text didn't overwrite the username field when uploading benchmarks for me. I use my real name when logging into my machine since I don't expect it to be leaked online. I guess I learn things the hard way.

Is there some sort of way to replace names in the database?

From what I can tell, the data is stored in the GitHub repo right here so people could just send a PR to remove it. But the problem is that doing a PR to remove your real name directly associates your GitHub account with your real name. Ideally we have some anonymous way to remove real names from the database.

Also, the git history repo still has the real name but I guess it's better if it's not being hosted onto the internet. There are ways to erase things from history but I am not sure if the maintainer is ok with that.

**Comment by vladmandic** [comment]
download <https://vladmandic.github.io/sd-extension-system-info/pages/benchmark-raw.json> and send me the id of the record where you want the name replaced or blanked.

and yes, it will remain in git history. there are ways to remove records from git history, but it involves rewriting entire repository chain - not doing that unless its a highly critical info.

**Comment by vladmandic** [comment]
data provided separately and pruned. closing.
