### ISSUE TITLE
benchmark-raw.json contains public IPs

### ISSUE THREAD

**Issue by f0lie** [vladmandic/sd-extension-system-info#8]
https://github.com/vladmandic/sd-extension-system-info/blob/main/pages/benchmark-raw.json

It doesn't look like the [data js code](https://github.com/vladmandic/sd-extension-system-info/blob/main/pages/benchmark-download.js) doesn't use this IP information to calculate anything. So this data could be removed without impacting the data.

**Comment by vladmandic** [comment]
removed, data will be updated on the next scheduled run.

<https://github.com/vladmandic/sd-extension-system-info/blob/10a0b585bd70589c3556b2682499972aebccd872/pages/benchmark-download.js#L81-L91>
